#version 440
layout(binding = 0) uniform writeonly image2D colormap;
layout(binding = 1) buffer readonly colormap_indices {
  uint indices[640 * 480];
};
layout(binding = 2) buffer readonly colormap_values { vec3 values[256]; };
layout(local_size_x = 8, local_size_y = 8) in;

void main() {
  ivec2 idx = ivec2(gl_GlobalInvocationID.xy);
  uint uidx = gl_GlobalInvocationID.y * 640 + gl_GlobalInvocationID.x;
  imageStore(colormap, idx, vec4(values[indices[uidx]], 1.0));
}
