#version 440

layout(binding = 0) uniform writeonly coherent restrict image2D outImage;
layout(std430, binding = 1) readonly buffer Colors { vec4 map[256]; };

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

uint square(uint x) { return x * x; }

void main() {
  ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
  uint idx =
      (square(gl_GlobalInvocationID.x) + square(gl_GlobalInvocationID.y)) % 256;
  imageStore(outImage, coord, map[idx]);
}
