#version 440

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;
layout(std430, binding = 0) buffer Max {
  vec2 minmax;
  float maxima[];
};
layout(push_constant) uniform Stride { uint stride; };

void main() {
  uint i = gl_GlobalInvocationID.x;
  if (stride * i + stride / 2 < maxima.length()) {
    maxima[stride * i] =
        max(maxima[stride * i], maxima[stride * i + stride / 2]);
  }
  minmax.x = maxima[0];
}
