#version 440

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;
layout(std430, binding = 0) buffer Min {
  vec2 minmax;
  float minima[];
};
layout(push_constant) uniform Stride { uint stride; };

void main() {
  uint i = gl_GlobalInvocationID.x;
  if (i * stride + stride / 2 < minima.length()) {
    minima[stride * i] =
        min(minima[stride * i], minima[i * stride + stride / 2]);
  }
  minmax.y = minima[0];
}
