#version 440

layout(constant_id = 0) const uint NELEMENTS = 640 * 480;
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;
layout(std430, binding = 0) buffer Max { uint data[NELEMENTS]; }
maxima;
layout(push_constant) uniform Stride { uint stride; };

void main() {
  uint i = gl_GlobalInvocationID.x;
  if (stride * i + stride / 2 < NELEMENTS) {
    maxima.data[stride * i] =
        max(maxima.data[stride * i], maxima.data[stride * i + stride / 2]);
  }
}
